// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAecwgRbRE0B1kLsvAfcn9sRgEX4ljNxVk',
    appId: '1:690519587413:android:09b88ab8fc0770f47472dc',
    messagingSenderId: '690519587413',
    projectId: 'otp-verification-3-34f39',
    storageBucket: 'otp-verification-3-34f39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOpsMOH8BKUAxBZ8NK_52NwFt2e93FxXE',
    appId: '1:690519587413:ios:38c72a0587d680bb7472dc',
    messagingSenderId: '690519587413',
    projectId: 'otp-verification-3-34f39',
    storageBucket: 'otp-verification-3-34f39.firebasestorage.app',
    androidClientId: '690519587413-k1fq0b4lnitkb2v0khaso0mbd18am0b5.apps.googleusercontent.com',
    iosClientId: '690519587413-0alnck75r1ioh5n2cghssikhgedo0d1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.machineProject2',
  );

}